name: .NET Core Desktop for Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu environment

    env:
      Solution_Name: CRUDwithDapper.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install .NET Core SDK for Linux
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x  # Ensure the version is appropriate for your project

    # Restore dependencies
    - name: Restore Dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    # Build the solution
    - name: Build Solution
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-restore

    # Execute all unit tests (optional, remove if no test project exists)
    - name: Run Tests
      run: dotnet test ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-build

    # Upload build artifacts
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Artifacts
        path: bin/${{ matrix.configuration }}
