name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx (optional, for multi-platform builds)
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Replace with your DockerHub username secret
        password: ${{ secrets.DOCKER_PASSWORD }}  # Replace with your DockerHub password secret

    - name: Build Docker image
      run: |
        docker build -t d3k010/dotnetprojects:latest -f CRUDwithDapper/Dockerfile .
      working-directory: ./  # Set the working directory to the root of your repo

    - name: Push Docker image
      run: |
        docker push d3k010/dotnetprojects:latest
